#!/usr/bin/env bash

## Install Ansible
apt-add-repository -y ppa:ansible/ansible
apt-get update -y
apt-get install -y curl git software-properties-common ansible

## POSIX Collection Used For Setting Authorized Key
# sudo ansible-galaxy collection install ansible.posix

## Pull Ansible Script (Ansible Pull Auto Executes)
sudo ansible-playbook local.yml 
