- hosts: localhost
  vars:
    node_lts: "16.13.1"

    ssh_key_encryption_algorithm: "id_ed25519"
    ssh_source_directory: "./.ssh"
    ssh_destination_directory: "{{ lookup('env', 'HOME') + '/.ssh' }}"

    public_ssh_key_source: "{{ ssh_source_directory + '/' + ssh_key_encryption_algorithm + '.pub' }}"
    public_ssh_key_destination: "{{ ssh_destination_directory + '/' + ssh_key_encryption_algorithm + '.pub' }}"

    private_ssh_key_source: "{{ ssh_source_directory + '/' + ssh_key_encryption_algorithm }}"
    private_ssh_key_destination: "{{ ssh_destination_directory + '/' + ssh_key_encryption_algorithm }}"

    neovim_version: "v0.6.1"

  pre_tasks:
    - name: Update Apt
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/core.yml
    - include: tasks/zsh.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/nvim.yml
    - include: tasks/customization.yml
