- name: Installing Stow
  apt: 
    name: stow
  tags:
    - install
    - dotfiles

- name: Clone .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ohearonkg/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Stow Dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles

