- name: Installing Stow
  apt: 
    name: stow
  tags:
    - install
    - dotfiles

- name: Clone .dotfiles
  ansible.builtin.git:
    repo: https://github.com/ohearonkg/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags:
    - install
    - dotfiles

- name: Stow Dotfiles
  ansible.builtin.shell: 
    cmd: "cd {{ lookup('env', 'HOME') }}/.dotfiles && ./install"
  tags:
    - install
    - dotfiles
