- name: Add I3 Gaps Apt Repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    state: present
    update_cache: true
  tags:
    - install
    - productivity

- name: Install I3 
  become: true
  apt:
    name: ["i3status", "i3lock", "i3-gaps", "i3lock", "dmenu"]
  tags:
    - install
    - productivity

- name: Install Tmux
  become: true
  apt:
    name: tmux
  tags:
    - install
    - productivity

- name: Add Alacritty Apt Repository
  ansible.builtin.apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present
    update_cache: true
  tags:
    - install
    - productivity

- name: Install Alacritty
  apt:
    name: alacritty
  tags:
    - install
    - productivity

- name: Download RipGrep
  become: true
  ansible.builtin.get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
    dest: /usr/local/bin/ripgrep_13.0.0_amd64.deb
  tags:
    - install
    - productivity

- name: Install RipGrep
  become: true
  apt:
    deb: /usr/local/bin/ripgrep_13.0.0_amd64.deb
  tags:
    - install
    - productivity

- name: Cleanup RipGrep Installation
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/ripgrep_13.0.0_amd64.deb
    state: absent
  tags:
    - install
    - productivity

- name: Download Bat
  become: true
  ansible.builtin.get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.18.3/bat_0.18.3_amd64.deb
    dest: /usr/local/bin/bat.deb
  tags:
    - install
    - productivity

- name: Install Bat
  become: true
  apt:
    deb: /usr/local/bin/bat.deb
  tags:
    - install
    - productivity

- name: Cleanup Bat Installation
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/bat.deb
    state: absent
  tags:
    - install
    - productivity

- name: Install Tree
  become: true
  apt:
    name: tree
  tags:
    - install
    - productivity

- name: Install XClip
  become: true
  apt:
    name: xclip
  tags:
    - install
    - productivity
