- name: Install ZSH
  apt: 
    name: zsh
  tags: 
    - install
    - zsh
    - dotfiles

- name: Change shell to zsh
  become: true
  ansible.builtin.shell: 
    cmd: usermod --shell /bin/zsh {{ lookup('env', 'USER') }}
  tags: 
    - install
    - zsh
    - dotfiles

- name: Download Starship Prompt
  become: true
  ansible.builtin.get_url: 
    url: https://starship.rs/install.sh
    dest: /usr/local/bin/starship-install.sh
  tags: 
    - install
    - zsh
    - dotfiles

- name: Install Starship Prompt
  ansible.builtin.shell: 
    cmd: cat /usr/local/bin/starship-install.sh | sh -s -- -y -f
  tags: 
    - install
    - zsh
    - dotfiles

- name: Cleanup Startship Install Script
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/starship-install.sh 
    state: absent
  tags: 
    - install
    - zsh
    - dotfiles

- name: Delete Default ZSH Config
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: absent
  tags: 
    - install
    - zsh
    - dotfiles

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.zsh/zsh-autosuggestions
  tags: 
    - install
    - zsh
    - dotfiles
